# Use an appropriate base image from GHCR
FROM ghcr.io/your-org/openjdk:17-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file into the container
COPY target/patient-service-0.0.1-SNAPSHOT.jar /app/patient-service.jar

# Start the application
CMD ["java", "-jar", "/app/patient-service.jar"]
